apiVersion: v1
kind: Secret
metadata:
    name: n8n
    namespace: homelab
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:msV/eavBXBGn0SoqlpeW/bKYM087Y3SyLaz4uLNF69Y=,iv:rJyT9gRTmSqlTPXpREfKjK1Jnp2Us8XrWbuV7U1CSTU=,tag:R0R1UU3yG5vOEH72IwRiTg==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NjBJM0todVg1Rm1LNExr
            Zk10TS95c2l5aThWMVduTEJwUFFLYytkRndJCmJ6R3ZVZHhBb2xhZFB2K2phUjd3
            K3VyaVovd3hTclAxbGJIVEIrS3dzTVUKLS0tIG1vMFlmYVNYYWVad2tEa0VoK1B4
            Snpoa3ZOOVp3WHRkV0V4WW9FZVRuM28KT2iRwvb+Acmo/Li4K4oSjUkudlQ9DDlz
            jSG2SdPBggwiIAgR/LMuECOsHbfj7YXPKNBKI41p1QMz/8vKSUIXxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:13:16Z"
    mac: ENC[AES256_GCM,data:++mYG8SKnFKxRoetru18vKUTVOI5Mew/kQeHtUNMKDVH5bPQhdnXzSxSH7qqeCosZUwvT/Eh6IAT2MDYa87TsmVD4l0sOTSpSZLNrankojriN+oP3R6GRAPoBR7tjY6t6wnb66htDJY35vNBsfcWIOY+uQSIXi9xVe2r9IxXkNQ=,iv:PhCiK3AVqPSFr2cGXe1J2gsDp5Mm/PrmpT8f6qsBN9k=,tag:yI2vRXxC/f7K9khAJILvFg==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
