---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
  namespace: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden
    kind: ClusterSecretStore
  target:
    name: n8n
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: REDACTED
        property: N8N_ENCRYPTION_KEY
