apiVersion: v1
kind: Secret
metadata:
    name: n8n
    namespace: homelab
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:jNsqVO+u67pbF7TXN+1fn+0Fakz4a3W2LEsu0a486iY=,iv:jJ8akux657fQ7PsqRk01XifC3g/SOXiXSr9cla67m6M=,tag:7OdcxHLA5frzkA2n62Ac2g==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU3FTVit2U0Jqc1NEU2lB
            eEJCSEM2Ly96dTZlcXBjajdJcUwrWVhYUW5FCjhZYXNVQ3BFemFFUis3RnIxRjVD
            cFJXT2ZOTFFYYzZ4bmZRTCtJeU5YS3MKLS0tIHJtZmdla1hpWi94K3RTeGgvM2tD
            S3RkNm5Jb1ZxVWFIcmFZMnI5MWVlWkEKq93LAPshmN7XgDinfMr1/4VPpzZsKFwc
            pod8WilZdDbxwIoheUlDoYH2dbdS1Z0xlAAhPOQ+MRFaBvqvHXyIxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T19:36:40Z"
    mac: ENC[AES256_GCM,data:KukTfeh1ozGiCGtPWgHa/j43mBYdp6sifZyyKzvEtbbgWk5bHDGXmG7ZXqHV9eBu5Ufq0Jb3R78UCoDQqEYoFFsqlAwM0X+i8m+u6pisMKYFWwzRWbii2VofYPGIWE+IdjyPx2uxaCcKww6tgSYhnkWHFYMhX1hCCZh9Yjvj0BA=,iv:6yjXFRTU+RLmxr/sAgASqMKoLJNYKMPjgO1F6h+2xTc=,tag:3ixMnluCVzHVI9wIzoPlqw==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
