apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:0XP6sUNULsPmi/30UltTCh+oFVQi0ulYSDw2xloE+vJub3Y6gbVcxQ==,iv:IVRhopak6DhlEWw6pJmAUyE+ude6Mm8W0q5bgqbZK84=,tag:J3l3CfNU9vhdJU7qCrfPXw==,type:str]
    email: ENC[AES256_GCM,data:KtTz1Gv1SGsNBHBLjU/sZUaxIyee4roOBAVDZlQ=,iv:MW/3b+PK2G9J9LGwZVJFfztkkPcSHL6EtMwcos9b7dw=,tag:5+9ZJbokThIA9M8NTfduzA==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWHlyb3drY2M0MnYyT3V4
            UGQ4WFBEOHFoYkw0MXl2SlBXS0V2UnY0eTFzCjJ4OXgzNE9ueFRQekhiY1ZtZUFj
            SlBKVzBVMjl5L0FBRE1wY21qMi9WZncKLS0tIG5RUE9KeFdzd0dhM2VOeFNpMmgw
            QUpqNnlOb2ova3VManNWcHNPN2FrSU0KTfqcEw8sC3QB2SIqSBMXLPPw1u7TuyW6
            YwZ4Rm4NC1FAlw5OZpXGQ891aEVavLG/T7QhAFIgXCmScc9yCcxFWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:52:38Z"
    mac: ENC[AES256_GCM,data:uAZgr0FmTMl7/lLfJEk5O2VRzfANwfWJmvhNrlL215Bxl+IzJeo+76H1zduvTLM0Z26IQ8i+MVwovyx/kse+PPgkcjj8pbxH44zTmiOQMVqeiBuemkf0fkBSQKlhbkHKv3ZSwHp+stv0fGPII0tNrLz9jDnUUEuEKssCQMbVMng=,iv:WpNO2deeTi2/NCRb4TzsIe09XBzDFEUCle5xRTWm1Ds=,tag:qGTtYXaoeS7azsLMvdHkyA==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
