apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:n3YJt4JaeMdzQQPnd7DB4D1DqmLPI6Xa5C7UB1mjwIOLevzP4NIynA==,iv:UHhrpRZgOFyXyz98Cm7mPbzej0BNeis/LreKuwo6rUs=,tag:1OEmzpIWd8ajb4uVQv7b3A==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2blBoN0dvVFVxeUFsMlgw
            VDVjd0wzeVpiUkZoVGNRWmMzUCtCVGtROXljCkMyblNGYmdwTjVHRXBRbTdadlBZ
            dHpWOFRPT3A4ZVhRc0twZW02UkF3aTQKLS0tIFRrWGNRazl2OUdHcG05Sm10TDBS
            Wk5lVCtkVkNXdE1HR2hlcVBvaW52OHMKtsEce8F+67FUCf1tUkoD2zFWqcEnc1s0
            XM+jtJBMGsw0e5o/6YX7TXjZy2dKxptfSW76fV9xWdN2Rsqt33bP5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T18:42:20Z"
    mac: ENC[AES256_GCM,data:v0mxjI2PZAFpZYfgpEIjmTZ8PQBltfxbLtprIyC/ISHjZOwG6y+8EJSlCKJDNQg95FemP0l0MqjRi9L8GcCxv6o3J4Ahix0iXHKKDRBKkVQ7u8zb1sYYULsCekWCnRutUbeLMAYXC177UpNgWCTrpc4JTNkFGwtf1LgAoNjm18c=,iv:NQ/l3f6YnxYnT8t8tIPHwGMxWKOkBF37wfxaq+AFmU8=,tag:+KViNejMKHUmUhbDFp//Og==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
