apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:hkwut3MtnJ1aQ2zJE86APBO3Z4cO1qyo0XYMBGag+oDDfQIsfkdNMw==,iv:i+I9KwNa2LzByNMdPRiz+osTLn6LCKE0NGkQfHfNiqQ=,tag:QA7HVgxBDXRfBXEI4LYqhQ==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZFl0STl6MGZwL1FlY0Qw
            Ky9NdWpxK3ZBUXBpK3pPeE82SFppcENGQUZRClNXblRYZ0c0dVRyZlpuSEdsR2M3
            MEw4b25ucWZwSlFuK0dYNGh1blBaTVkKLS0tICtMdVh1djM0dUl3cmt6M3l4MlF6
            ek9VVXgySmhIR0tGZGFUeTgxaG4yOGsKnnclwCYKkMHIu4rG78Uc0hcmdsjnkjjx
            fNY4S5IPv8BYEOfrXVbSLMweiA98xWU4zLCYDnRgD0PaS5yqVONT4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T19:36:40Z"
    mac: ENC[AES256_GCM,data:yKqGr6iJJNnuE30ROLgfa0kknjm5MUh3UpC86CBuMbzT0Vu2aAqUPaaS1lL2jtALFnEVNtSk+4YQ9z2w+i2KJwcFqyFSWbo/fyOuhymY6yjVucZlwRwhUzDP/vAnFZl+qBy5nN/uwdL5htwgxV2mLlGgcSGtYFFTLgwzG58Ee+Q=,iv:M7Y53Q2VTboUUMVpAJrl1ckR23vtEqjQxn+osMYxwkQ=,tag:Wbz9McJkCNL75lerdVETAw==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
