apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:n8va+d5KYQdx/vnoJuBQGxLew1hKBebWAJQGz0kdshNKhrGTPIgkh/wPCfWb4mC1dO0/f2y/MZkv8JzM0JddEMQepcvZR3AWi/IGWYGSN00jvlIDSQftMpUFJ5k9,iv:sFzoSxTlEAlMmiOzSGBaPZz1ODtteem1n2phwAhJGQs=,tag:bLpVA8kFitzSlnt3W3EVlA==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaDFyZDM2WHJFUit0UjJ1
            RTMzL3RSYU9FNnhHNE9hRmNwUWJ6ZVgyQkFrCkNodHlkTjJMYXo0R01TMldlR3JQ
            VzNibllMc1RVQ0NLMXF1b0Eyd1U1Z00KLS0tIFAvOVJDeXFLaGZuYkFsb1JtZkFw
            R2gxdjdTQzduVEhEMG5qL0RxbHc5ajAKnaU6g5jVpIShU6sCyXO3FJOUaaKnyG4W
            eMHsQ/z24VHFxOXZ24yOdFFwvgOLJnPosORzF4DrZsd2wSHfdevNmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:33:03Z"
    mac: ENC[AES256_GCM,data:JvH81Mpcaxua4/0HfW5VnlrOCw0bSGhDj4+10HT7rLH5pQcq26NP/9HkJdy4HVZP1YmgBO5/u4hD8+pKf1LxHD3pPXFgYB8eYu/PbQxadBGadz8jvk4l3MYueuNc3hk9ESvXgHK09NipZVUUmUqVSWbuXas/zKREHj/JTaV7Ehs=,iv:N7r/jE2ADo9qOY4w4LCjhJsFCLvbvimwEvA0dMKN5zI=,tag:wBFgfDhdcmQDPY5JDAeIJQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
