apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4KaLb2K+OgHazZPsrkWhTiU3ZA1w+Gt8gmLL2GLPWIEHbXqUc+tzTHk4Eapyx2N3gU1Fulm2eUdCbNdHxOkjl935rWddqxnLsmh+I6ecqdTDT1jquEwbw0jeLBZo,iv:akdl0tSfWfsT7oDk0xDOlBN83f4LvmZmMIxUPzD8cxQ=,tag:J+vR1gqWlcssJSb+VnJEXA==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQWtwVS8xTjF2bHVPTzVM
            VXZLbjc2TkhjNXRBb3NpYWMwQ0hWUFAySGxjCnlURy9vbkxFV2JmdG93VmMvZ2dN
            Uko2ZVl6S0RzTWJIbkFNekt6U1pFajAKLS0tIGJJcExKSGltWEw3TmFVT0VwK2pn
            QzJpOTV6dHZlM1UxTjhuVkI2bzdiMEkKuWIqP7hx5TR/ZbaNwhghhGDBhsM4GCK0
            NmCDtlnFntHXlmjy/ZLVhpMTgqODDCcLbC7bpPqzRaCO6iQ/8VOalg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:18:56Z"
    mac: ENC[AES256_GCM,data:jlSQnvTIXtZYCqec8L2+cWhUBlBSGHgnwDT12OXlBV5smPpNUuDt0Z3GqjMJgf8f38UqTtrzHURA00QNz7I2qwtwRjn1DqHKG0FqyneOfaH7ECGMjlMcSb9tphUQYCZf65IQfu28J86BfNbnNHPuLeFH/0kgm2hB9KaBw4o5w3s=,iv:2oc+QYEIRlBCi1u4oEwjWGvV+JPNd+cBSDUPbs468dw=,tag:yXhLLp2jyYGVDAs25t52hQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
