apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:62ENgnAEW5287kTKF7dqjUQw+PqotaP3mH23df7q3Wzes6+uZVmXuPPulAftRZgw3cJkgLUT/BU=,iv:xDmZzuz7cujtJEzg2RHKguQ7Cp9X89fkzLEP5wYmgIo=,tag:9TEmPwR7UBVFBVnDAiOaEg==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbDZhN1UxWTVrWmdRV3Nn
            SWhhWjBvRFFzR0hObndxOHYxdTVjYytYSm5nCjJHUE5YbWo0YjErRXBpY0JBVGRC
            cnAyOENkaC9xZFZVa0czemhQc3VZd2cKLS0tIHJmVEdiNlo0NUlKcEk5ZFdMcjZO
            QmhDK0JZbWk4ekwrRHZadTI0MFZOY3MKKnpXIS/K6b3zMqp8oBW618aPHPiTcAsC
            mva17onrQ9sBJ0II1QDoAMu/l/HvQJcvjvnwdcY0fdmtgNxR810HXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T05:12:50Z"
    mac: ENC[AES256_GCM,data:Sk4d6MI3NEZyKqWxLoPWksvwz/an69kMxCI+c/cQ2YAutaSaU+tSPahi3+supkM65r1jJw838IiursIqJPPpBeEFBUEYOF0C12sbMUj4THOF+8NN75R8BUtQQeY8vgrveEc7ZE6hkw3mEMJbCdONMd/IpRd/Qcozx7BzGwFLq0A=,iv:sUAwQsgzs8NkabMDn7/48Ck0WLJNKr3NwJqVQyv3ZdU=,tag:DF9jxzkVmv+Nik4tc+OjSQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.12.1
