apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:OHB2j8ud2TkJ6W/kiBtyzhHNJTjeUNNQ/3U7DWI80XiMYvhAQ8ajEw==,iv:c1/WuXwSftDaYbhvQdtfdmNcmeswzxs1l4gSeXKEznc=,tag:3PubW2++gxxAd468JhpcjQ==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGZ5MzFpWGwwaGZpNU9l
            dStXdm1ZWEpURCtnZWZKN0h1aDNyTnFDRzFNCjdLRkovQzZvaWV6UTFwVG16aFB4
            enU4Zm9EL0M4Z3RvVER4OW8xQTMra2MKLS0tIEV3bzVVSG41NGNoMU5DQnpkR1hu
            d0V1TVZGd3Z5UnBRR2o1Q1FSc2dqWkkKetrur38XHbNOK1v7Ze/OFw4V7AgQlB/J
            9bn8+Igdh+WnoAzajrWvyWpMGjm18Mis3ZTGZvFwF3WxI9iiex3dOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T05:18:26Z"
    mac: ENC[AES256_GCM,data:HmuNQzlfkPATuIzKmc/NScr47SQ8RqHvLz41bAJDnvp/0pdaskiBoMIkaJoSyXhdYye5Klp/YqX63IDZON2GeZbuzzR+ucDEBQuQU0Uy66zAzXktEAQBUaF8XhDAmJbo2HVDlIQFOBJfPORYE+VJ9ZWSPFKsH4zUl+iXk+uGvNo=,iv:ka/ACFpM1BdiDv15x0VdNe/UxuZnlcGGvlvLIhOzORA=,tag:QrHQs2wjCKMqdRsUbGCaFA==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.12.1
